#decorations = "none"
import = ["/home/mkanatsu/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "PlemolJP Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Itali"

[font.italic]
family = "PlemolJP Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[window]
opacity = 0.75
