#[[plugins]]
#repo = 'thinca/vim-splash'

# Must have at least

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if   = '''has('nvim')'''
hook_post_update = ':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo     = 'Shougo/echodoc.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-echodoc.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build   = 'make'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-lightline.vim'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# color scheme
[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = 'source ~/.vim/rc/plugins/plugin-treesitter.vim'

[[plugins]]
repo = 'tanvirtin/monokai.nvim'

[[plugins]]
repo = 'vigoux/oak'
hook_add = 'let g:oak_virtualtext_bg = 1'

[[plugins]]
repo = 'sainnhe/sonokai'

# tags
[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-seiya.vim'

# pandoc markdown
[[plugins]]
repo      = 'vim-pandoc/vim-pandoc'
hook_add  = 'source ~/.vim/rc/plugins/plugin-vim-pandoc.vim'

[[plugins]]
repo      = 'vim-pandoc/vim-pandoc-syntax'

## syntax checker
#[[plugins]]
#repo       = 'dense-analysis/ale'
#if         = '''has('nvim') || has('job') && has('channel') && has('timers')'''
#hook_add   = 'source ~/.vim/rc/plugins/plugin-ale.vim'

# ime
[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-eskk.vim'

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/rc/plugins/plugin-indent-guides.vim'

# english words dictionary
[[plugins]]
repo = 'koron/codic-vim'
