# Complete/Language Server Protocol
[[plugins]]
repo        = 'Shougo/ddc.vim'
on_event    = 'InsertEnter'
hook_source = 'source ~/.vim/rc/plugins/plugin-ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-around'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-matcher_head'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-sorter_rank'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-nvim-lsp'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'LumaKernel/ddc-file'
on_source   = 'ddc.vim'

# Neovim builtin LSP server
[[plugins]]
repo        = 'neovim/nvim-lspconfig'
on_event    = 'BufEnter'
hook_source = 'source ~/.vim/rc/plugins/plugin-nvim-lsp.vim'

[[plugins]]
repo        = 'williamboman/nvim-lsp-installer'
on_source   = 'nvim-lspconfig'
hook_source = 'source ~/.vim/rc/plugins/plugin-nvim-lsp-installer.vim'

[[plugins]]
repo        = 'matsui54/ddc-nvim-lsp-doc'
on_source   = 'ddc.vim'
hook_source = 'source ~/.vim/rc/plugins/plugin-ddc-nvim-lsp-doc.vim'

# grammer checker ( need Java runtime for LanguageTool )
[[plugins]]
repo       = 'rhysd/vim-grammarous'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# translation
[[plugins]]
repo       = 'daisuzu/translategoogle.vim'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']
hook_add   = 'source ~/.vim/rc/plugins/plugin-translategoogle.vim'

# writing table in plain text
[[plugins]]
repo       = 'dhruvasagar/vim-table-mode'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# TeX
[[plugins]]
repo        = 'lervag/vimtex'
hook_add   = 'source ~/.vim/rc/plugins/plugin-vimtex.vim'
on_ft       = ['tex', 'plaintex']

# vimshell
[[plugins]]
repo        = 'Shougo/vimshell'
on_cmd      = ['VimShell', 'VimShellCreate', 'VimShellPop']
hook_add    = 'source ~/.vim/rc/plugins/plugin-vimshell.vim'

# Gist
repo        = 'lambdalisue/vim-gista'
on_cmd      = 'Gista'
hook_add    = 'source ~/.vim/rc/plugins/plugin-vim-gista.vim'

# asm
[[plugins]]
repo        = 'shiracamus/vim-syntax-x86-objdump-d'
on_ft       = ['asm']
