# complete
[[plugins]]
repo     = 'Shougo/neocomplete.vim'
on_i     = 1
if       = '''! has('nvim')'''

[[plugins]]
repo     = 'Shougo/deoplete.nvim'
dependes = ['FastFold']
on_i     = 1
if       = '''has('nvim')'''

[[plugins]]
repo     = 'Konfekt/FastFold'
on_i     = 1
if       = '''has('nvim')'''

[[plugins]]
repo     = 'Shougo/neco-syntax'
on_i     = 1

[[plugins]]
repo     = 'ujihisa/neco-look'
on_i     = 1

# grammer checker ( need Java runtime for LanguageTool )
[[plugins]]
repo     = 'rhysd/vim-grammarous'
on_ft    = ['rst', 'markdown', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# writing table in plain text
[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_ft    = ['rst', 'markdown', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# unite
[[plugins]]
repo      = 'h1mesuke/unite-outline'
on_source = ['unite.vim']

# vimshell
[[plugins]]
repo      = 'Shougo/vimshell'
on_cmd    = ['VimShell', 'VimShellCreate', 'VimShellPop']

# asm
[[plugins]]
repo      = 'shiracamus/vim-syntax-x86-objdump-d'
on_ft     = ['asm']

# c++
[[plugins]]
repo      = 'osyo-manga/vim-snowdrop'
on_ft     = ['c', 'cpp']

# haskell
[[plugins]]
repo      = 'ujihisa/ref-hoogle'
on_ft     = ['haskell']

[[plugins]]
repo      = 'ujihisa/neco-ghc'
on_ft     = ['haskell']

[[plugins]]
repo      = 'dag/vim2hs'
on_ft     = ['haskell']

# rust
[[plugins]]
repo      = 'wting/rust.vim'
on_ft     = ['rust']

# ansible yaml
[[plugins]]
repo      = 'chase/vim-ansible-yaml'
on_ft     = ['ansible']

# tweetvim
[[plugins]]
repo      = 'basyura/TweetVim'
depends   = ['twibill.vim', 'bitly.vim', 'open-browser.vim', 'webapi-vim', 'unite.vim' 'unite-outline']
on_cmd    = ['TweetVimSay', 'TweetVimUserStream']
on_map    = '<Plug>(tweetvim)'

[[plugins]]
repo      = 'basyura/twibill.vim'
on_source = ['TweetVim']

[[plugins]]
repo      = 'basyura/bitly.vim'
on_source = ['TweetVim']

[[plugins]]
repo      = 'tyru/open-browser.vim'
on_source = ['TweetVim']

[[plugins]]
repo      = 'mattn/webapi-vim'
on_source = ['TweetVim']

[[plugins]]
repo      = 'yomi322/neco-tweetvim'
depends   = ['neocomplete']
on_source = ['TweetVim']
if        = '''! has('nvim')'''

[[plugins]]
repo      = 'yomi322/unite-tweetvim'
depends   = ['unite-outline']
on_source = ['TweetVim']
