#[[plugins]]
#repo = 'thinca/vim-splash'

# Must have at least

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc'
build   = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

# tags
[[plugins]]
repo = '5t111111/alt-gtags.vim'

# doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['webapi-vim']

# colorscheme
[[plugins]]
repo = 'vim-scripts/Colour-Sampler-Pack'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'miyakogi/seiya.vim'

# pandoc markdown
[[plugins]]
repo      = 'vim-pandoc/vim-pandoc'

[[plugins]]
repo      = 'vim-pandoc/vim-pandoc-syntax'

# ime
[[plugins]]
repo = 'tyru/eskk.vim'

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# english words dictionary
[[plugins]]
repo = 'koron/codic-vim'
