#[[plugins]]
#repo = 'thinca/vim-splash'

# Must have at least

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-dein.vim'

[[plugins]]
repo     = 'Shougo/echodoc.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-echodoc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lua_add = '''
    require("plugin-lualine")
'''

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo        = 'williamboman/mason.nvim'
lua_add     = '''
    require("mason").setup()
'''


# color scheme
[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'tanvirtin/monokai.nvim'

[[plugins]]
repo = 'vigoux/oak'
hook_add = 'let g:oak_virtualtext_bg = 1'

[[plugins]]
repo = 'rktjmp/lush.nvim'

#[[plugins]]
#repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
repo = 'ChristianChiarulli/nvcode-color-schemes.vim'

[[plugins]]
repo = 'sainnhe/sonokai'

# transparency

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-seiya.vim'

# pandoc markdown
[[plugins]]
repo      = 'vim-pandoc/vim-pandoc'
hook_add  = 'source ~/.vim/rc/plugins/plugin-vim-pandoc.vim'

[[plugins]]
repo      = 'vim-pandoc/vim-pandoc-syntax'

# bitbake
[[plugins]]
repo        = 'kergoth/vim-bitbake'

## syntax checker
#[[plugins]]
#repo       = 'dense-analysis/ale'
#if         = '''has('nvim') || has('job') && has('channel') && has('timers')'''
#hook_add   = 'source ~/.vim/rc/plugins/plugin-ale.vim'

# ime
[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = 'source ~/.vim/rc/plugins/plugin-eskk.vim'

# english words dictionary
[[plugins]]
repo = 'koron/codic-vim'
