# Complete/Language Server Protocol
[[plugins]]
repo        = 'Shougo/ddc.vim'
on_event    = 'InsertEnter'
depends     = 'pum.vim'
hook_source = 'source ~/.vim/rc/plugins/plugin-ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-around'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-matcher_head'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-sorter_rank'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/ddc-nvim-lsp'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'LumaKernel/ddc-file'
on_source   = 'ddc.vim'

# Text snippet
[[plugins]]
repo        = 'hrsh7th/vim-vsnip'
on_event    = 'InsertEnter'
depends     = 'vim-vsnip-integ'
hook_source = 'source ~/.vim/rc/plugins/plugin-vim-vsnip.vim'

[[plugins]]
repo        = 'hrsh7th/vim-vsnip-integ'
on_source   = 'ddc.vim'

[[plugins]]
repo        = 'Shougo/pum.vim'
on_source   = 'ddc.vim'

# Neovim builtin LSP server
[[plugins]]
repo        = 'neovim/nvim-lspconfig'
on_event    = 'BufEnter'
depends     = ['lspkind-nvim', 'lsp_signature.nvim', 'nvim-lsp-installer']
hook_source = 'luafile ~/.vim/rc/plugins/lua/plugin-nvim-lsp.lua'

[[plugins]]
repo        = 'ray-x/lsp_signature.nvim'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'onsails/lspkind-nvim'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'folke/trouble.nvim'
on_source   = 'nvim-lspconfig'
hook_source = 'luafile ~/.vim/rc/plugins/lua/plugin-trouble.lua'

[[plugins]]
repo        = 'williamboman/nvim-lsp-installer'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'matsui54/denops-popup-preview.vim'
on_source   = 'nvim-lspconfig'
depends     = ['nvim-lsp-installer', 'pum.vim']
hook_source = 'source ~/.vim/rc/plugins/plugin-denops-popup-preview.vim'

# color scheme with tree-sitter
[[plugins]]
repo             = 'nvim-treesitter/nvim-treesitter'
on_event         = 'BufEnter'
hook_source      = 'luafile ~/.vim/rc/plugins/lua/plugin-treesitter.lua'
depends          = 'nvim-ts-rainbow'
hook_post_update = 'TSUpdate'

[[plugins]]
repo      = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'

# indent
[[plugins]]
repo         = 'lukas-reineke/indent-blankline.nvim'
on_event     = 'BufEnter'
depends      = 'nvim-ts-rainbow'
hook_source  = 'luafile ~/.vim/rc/plugins/lua/plugin-indent-blankline.lua'

# grammer checker ( need Java runtime for LanguageTool )
[[plugins]]
repo       = 'rhysd/vim-grammarous'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# translation
[[plugins]]
repo       = 'daisuzu/translategoogle.vim'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']
hook_add   = 'source ~/.vim/rc/plugins/plugin-translategoogle.vim'

# writing table in plain text
[[plugins]]
repo       = 'dhruvasagar/vim-table-mode'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# TeX
[[plugins]]
repo        = 'lervag/vimtex'
hook_add   = 'source ~/.vim/rc/plugins/plugin-vimtex.vim'
on_ft       = ['tex', 'plaintex']

# vimshell
[[plugins]]
repo        = 'Shougo/vimshell'
on_cmd      = ['VimShell', 'VimShellCreate', 'VimShellPop']
hook_add    = 'source ~/.vim/rc/plugins/plugin-vimshell.vim'

# Gist
repo        = 'lambdalisue/vim-gista'
on_cmd      = 'Gista'
hook_add    = 'source ~/.vim/rc/plugins/plugin-vim-gista.vim'

# asm
[[plugins]]
repo        = 'shiracamus/vim-syntax-x86-objdump-d'
on_ft       = ['asm']
