# Complete/Language Server Protocol
[[plugins]]
repo        = 'Shougo/ddc.vim'
on_event    = ['InsertEnter', 'CmdlineEnter']
depends     = ['context_filetype.vim', 'pum.vim']
hook_source = 'source ~/.vim/rc/plugins/plugin-ddc.vim'

[[plugins]]
repo        = 'Shougo/pum.vim'

[[plugins]]
repo        = 'Shougo/ddc-ui-pum'
on_source   = 'ddc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/neco-vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
lazy = 0

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
lazy = 0

[[plugins]]
repo = 'Shougo/ddc-around'
lazy = 0

[[plugins]]
repo        = 'Shougo/ddc-matcher_head'
lazy        = 0

[[plugins]]
repo        = 'Shougo/ddc-converter_remove_overlap'
lazy        = 0

[[plugins]]
repo        = 'Shougo/ddc-sorter_rank'
lazy        = 0

[[plugins]]
repo        = 'Shougo/ddc-zsh'
lazy        = 0

[[plugins]]
repo        = 'Shougo/ddc-nvim-lsp'
lazy        = 0

[[plugins]]
repo        = 'Shougo/ddc-source-nvim-lsp'
lazy        = 0

[[plugins]]
repo = 'tani/ddc-fuzzy'
lazy = 0

[[plugins]]
repo        = 'LumaKernel/ddc-file'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-buffer'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-dictionary'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-filter_editdistance'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-converter_truncate'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-postfilter_score'
lazy        = 0

[[plugins]]
repo        = 'matsui54/ddc-ultisnips'
lazy        = 0

[[plugins]]
repo        = 'gamoutatsumi/ddc-emoji'
lazy        = 0

[[plugins]]
repo        = 'matsui54/denops-popup-preview.vim'
on_source   = 'ddc.vim'
hook_source = 'source ~/.vim/rc/plugins/plugin-denops-popup-preview.vim'

[[plugins]]
repo        = 'matsui54/denops-signature_help'
on_source   = 'ddc.vim'
hook_source = 'source ~/.vim/rc/plugins/plugin-denops-signature_help.vim'

[[plugins]]
repo        = 'ray-x/lsp_signature.nvim'
if          = "has('nvim')"
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'shun/ddc-vim-lsp'
lazy        = 0

# Text snippet
[[plugins]]
repo        = 'hrsh7th/vim-vsnip'
on_source   = 'ddc.vim'
depends     = ['vim-vsnip-integ', 'friendly-snippets']
hook_add    = 'source ~/.vim/rc/plugins/plugin-vim-vsnip.vim'

[[plugins]]
repo        = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo        = 'rafamadriz/friendly-snippets'

