# Neovim builtin LSP server
[[plugins]]
repo        = 'neovim/nvim-lspconfig'
on_event    = 'BufEnter'
depends     = ['lspsaga.nvim']
lua_source  = '''
    require("plugin-nvim-lsp")
'''

[[plugins]]
repo         = 'jose-elias-alvarez/null-ls.nvim'
on_source    = 'nvim-lspconfig'
depends      = ['plenary.nvim']
lua_source   = '''
    require("plugin-null-ls")
'''

#[[plugins]]
#repo        = 'simrat39/rust-tools.nvim'
#depends     = 'nvim-lspconfig'
#on_ft       = 'rust'
#hook_source = 'luafile ~/.vim/rc/plugins/lua/plugin-rust-tools.lua'
#

[[plugins]]
repo        = 'tami5/lspsaga.nvim'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'folke/trouble.nvim'
on_source   = 'nvim-lspconfig'
depends     = 'nvim-web-devicons'
lua_source  = '''
    require("plugin-trouble")
'''

[[plugins]]
repo        = 'kyazdani42/nvim-web-devicons'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'williamboman/mason-lspconfig.nvim'
on_source   = 'nvim-lspconfig'

[[plugins]]
repo        = 'nvim-lua/plenary.nvim'
on_event   = 'BufEnter'

[[plugins]]
repo        = 'nvim-lua/popup.nvim'
depends     = 'plenary.nvim'
on_source   = 'plenary.nvim'

[[plugins]]
repo        = 'nvim-telescope/telescope.nvim'
depends     = 'plenary.nvim'
on_source   = 'plenary.nvim'

# color scheme with tree-sitter
[[plugins]]
repo             = 'nvim-treesitter/nvim-treesitter'
on_event         = 'BufEnter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo      = 'p00f/nvim-ts-rainbow'
depends   = 'nvim-treesitter'
on_source = 'nvim-treesitter'
lua_source       = '''
    require("plugin-treesitter")
'''

# indent
[[plugins]]
repo         = 'lukas-reineke/indent-blankline.nvim'
on_event     = 'BufEnter'
on_source    = 'nvim-treesitter'
lua_source   = '''
    require("plugin-indent-blankline")
'''

# grammer checker ( need Java runtime for LanguageTool )
[[plugins]]
repo       = 'rhysd/vim-grammarous'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# translation
[[plugins]]
repo       = 'daisuzu/translategoogle.vim'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']
hook_add   = 'source ~/.vim/rc/plugins/plugin-translategoogle.vim'

# writing table in plain text
[[plugins]]
repo       = 'dhruvasagar/vim-table-mode'
on_ft      = ['rst', 'markdown', 'asciidoc', 'pandoc', 'gitrebase', 'gitcommit', 'vcs-commit', 'hybrid', 'text', 'help', 'tex']

# TeX
[[plugins]]
repo        = 'lervag/vimtex'
hook_add    = 'source ~/.vim/rc/plugins/plugin-vimtex.vim'
on_ft       = ['tex', 'plaintex']

# Asciidoc (w/ asciidoctor)
[[plugins]]
repo        = 'habamax/vim-asciidoctor'
on_ft       = ['asciidoc']
hook_add    = 'source ~/.vim/rc/plugins/plugin-asciidoctor.vim'

# PlantUML
[[plugins]]
repo        = 'aklt/plantuml-syntax'
on_ft       = 'plantuml'

# vimshell
[[plugins]]
repo        = 'Shougo/vimshell'
on_cmd      = ['VimShell', 'VimShellCreate', 'VimShellPop']
hook_add    = 'source ~/.vim/rc/plugins/plugin-vimshell.vim'

# Gist
[[plugins]]
repo        = 'lambdalisue/vim-gista'
on_cmd      = 'Gista'
hook_add    = 'source ~/.vim/rc/plugins/plugin-vim-gista.vim'

# asm
[[plugins]]
repo        = 'shiracamus/vim-syntax-x86-objdump-d'
on_ft       = ['asm']

