[[plugins]]
repo = 'Shougo/ddu.vim'
merged = 0
on_source   = 'ddc.vim'
hook_source = '''
    source $XDG_CONFIG_HOME/nvim/rc/plugins/plugin-ddu.vim'
    call Ddu_setup()
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
lazy = 1
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
merged = 0

[[plugins]]
repo = 'Shougo/ddu-ui-filer'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
merged = 0

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'matsui54/ddu-source-man'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'

[[plugins]]
repo = 'matsui54/ddu-source-highlight'

#[[plugins]]
#repo = 'matsui54/ddu-source-dein_update'

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'gamoutatsumi/ddu-source-nvim-lsp'
