[font]
size = 8.0
hinting = "slight"
edging = "antialias"

[[font.normal]]
family = "Monaspace Argon"
style = "Regular"
[[font.normal]]
family = "BIZ UDゴシック"

[[font.italic]]
family = "Monaspace Radon"
style = "ExtraLight"
[[font.italic]]
family = "BIZ UDゴシック"
style = "Regular"

[[font.bold]]
family = "Monaspace Krypton"
style = "Light"
[[font.bold]]
family = "BIZ UDゴシック"
style = "ExtraLight"

[[font.bold_italic]]
family = "Monaspace Krypton"
style = "Light"
[[font.bold_italic]]
family = "BIZ UDゴシック"

[font.features]
"Monaspace Argon" = ["calt", "liga", "dlig", "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "ss09"]
"Monaspace Radon" = ["calt", "liga", "dlig", "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "ss09"]
"Monaspace Krypton" = ["calt", "liga", "dlig", "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "ss09"]
